import type { Category } from './types';
import { CubeIcon, CurrencyDollarIcon, CreditCardIcon, PuzzlePieceIcon, BanknotesIcon, ScaleIcon, WalletIcon, ChartBarSquareIcon, TableCellsIcon, LockClosedIcon, CalculatorIcon, DevicePhoneMobileIcon, PhotoIcon, PiggyBankIcon, ClipboardDocumentListIcon } from './components/icons/Icons';

export const LEARNING_PATH: string[] = [
  'inflation-visualizer',
  'fractional-reserve',
  'bitcoin-transaction',
  'ethereum-transaction',
  'layer-2-scaling',
  'self-custody',
  'seed-phrase',
  'wallet-overview',
  'nft-explained',
  'kyc-sim',
  'password-manager',
  'two-factor-auth',
  'fiat-deposit',
  'buy-and-withdraw',
  'crypto-withdraw',
  'wallet-connection',
  'swap-tool',
  'token-approval',
  'lending-borrowing',
  'liquidation-risk',
  'perpetual-futures',
  'airdrops-farming',
  'emergency-fund',
  'expense-tracking',
  'assets-liabilities',
  'debt-repayment',
  'portfolio-sim',
  'portfolio-tracker',
  'candlestick-chart',
  'coin-market-explorer',
];

export const GET_CATEGORIES = (t: (key: string) => string): Category[] => [
  {
    id: 'wallets',
    title: t('categories.wallets.title'),
    description: t('categories.wallets.description'),
    icon: CreditCardIcon,
    simulations: [
      {
        id: 'seed-phrase',
        title: 'Seed Phrase Creation',
        description: 'Practice creating and backing up a wallet seed phrase securely.',
        xp: 100,
        badge: 'Seed Phrase Master',
        isSecurityCritical: true,
      },
      {
        id: 'wallet-overview',
        title: 'Wallet Overview',
        description: 'Practice sending, receiving, and managing assets across different blockchains.',
        xp: 150,
        badge: 'Wallet Manager',
      },
      {
        id: 'self-custody',
        title: 'Self-Custody: Hot vs. Cold Wallets',
        description: 'Understand the critical differences between software and hardware wallets for security.',
        xp: 150,
        badge: 'Self-Custody Champ',
        isSecurityCritical: true,
      },
    ],
  },
  {
    id: 'blockchains',
    title: t('categories.blockchains.title'),
    description: t('categories.blockchains.description'),
    icon: CubeIcon,
    simulations: [
       {
        id: 'bitcoin-transaction',
        title: 'How Bitcoin Transactions Work (PoW)',
        description: 'Visualize a transaction from signing to Proof-of-Work mining and confirmation.',
        xp: 250,
        badge: 'BTC Transactor',
      },
      {
        id: 'ethereum-transaction',
        title: 'How Ethereum Transactions Work (PoS)',
        description: 'Visualize a transaction from signing to Proof-of-Stake validation and confirmation.',
        xp: 250,
        badge: 'ETH Transactor',
      },
      {
        id: 'layer-2-scaling',
        title: 'Layer 2 Scaling Solutions',
        description: 'Understand how technologies like Optimism & Base help Ethereum scale by processing transactions off-chain.',
        xp: 200,
        badge: 'Scale Specialist',
      },
    ],
  },
   {
    id: 'nfts',
    title: t('categories.nfts.title'),
    description: t('categories.nfts.description'),
    icon: PhotoIcon,
    simulations: [
        {
            id: 'nft-explained',
            title: 'NFTs Explained',
            description: 'Learn what NFTs are, their use cases beyond art, and how to mint and trade them.',
            xp: 150,
            badge: 'NFT Explorer',
        },
    ],
  },
  {
    id: 'fiat-inflation',
    title: t('categories.fiatInflation.title'),
    description: t('categories.fiatInflation.description'),
    icon: ScaleIcon,
    simulations: [
      {
        id: 'inflation-visualizer',
        title: 'Fiat vs. Crypto Visualizer',
        description: 'See how the value of $100 changes over time compared to Bitcoin.',
        xp: 50,
        badge: 'Inflation Aware'
      },
      {
        id: 'fractional-reserve',
        title: 'How Banks Create Money',
        description: 'Learn how fractional reserve banking expands the money supply.',
        xp: 100,
        badge: 'Money Multiplier'
      },
    ],
  },
  {
    id: 'banks-exchanges',
    title: t('categories.banksExchanges.title'),
    description: t('categories.banksExchanges.description'),
    icon: BanknotesIcon,
    simulations: [
      {
        id: 'kyc-sim',
        title: 'KYC Simulation',
        description: 'Go through the steps of an ID verification process without using real data.',
        xp: 75,
        badge: 'Verified User',
        isSecurityCritical: true,
      },
      {
        id: 'fiat-deposit',
        title: 'Deposit Fiat to Exchange',
        description: 'Learn how to transfer money from your bank to a crypto exchange, paying attention to critical details like reference codes.',
        xp: 75,
        badge: 'Fiat Depositor',
        isSecurityCritical: true,
      },
      {
        id: 'buy-and-withdraw',
        title: 'Buy & Withdraw Crypto',
        description: 'Practice buying crypto on an exchange and immediately withdrawing it to your own self-custody wallet for maximum security.',
        xp: 125,
        badge: 'Sovereign Owner',
        isSecurityCritical: true,
      },
      {
        id: 'crypto-withdraw',
        title: 'Withdraw Crypto to Fiat',
        description: 'Learn to move crypto from your wallet to an exchange to sell and withdraw to your bank.',
        xp: 125,
        badge: 'Fiat Withdrawer',
        isSecurityCritical: true,
      },
    ],
  },
  {
    id: 'dapps',
    title: t('categories.dapps.title'),
    description: t('categories.dapps.description'),
    icon: PuzzlePieceIcon,
    simulations: [
      {
        id: 'swap-tool',
        title: 'Simulated Swap Tool',
        description: 'Practice swapping tokens on a DEX simulator to understand fees and slippage.',
        xp: 150,
        badge: 'DeFi Swapper',
      },
       {
        id: 'wallet-connection',
        title: 'Wallet Connection',
        description: 'Learn how to connect your wallet to DApps in a safe test environment.',
        xp: 75,
        badge: 'Wallet Connector',
        isSecurityCritical: true,
      },
      {
        id: 'token-approval',
        title: 'Token Approval Simulation',
        description: 'Learn how to grant and manage token approvals for DApps, a key security concept.',
        xp: 125,
        badge: 'Approval Guardian',
        isSecurityCritical: true,
      },
      {
        id: 'lending-borrowing',
        title: 'Lending & Borrowing',
        description: 'Deposit assets to earn interest and use them as collateral to borrow other assets.',
        xp: 200,
        badge: 'DeFi Banker'
      },
      {
        id: 'airdrops-farming',
        title: 'Airdrops & Farming',
        description: 'Learn how to earn tokens through airdrops and by providing liquidity to DeFi protocols (yield farming).',
        xp: 175,
        badge: 'Yield Farmer',
      },
      {
        id: 'perpetual-futures',
        title: 'Perpetuals & Futures Contracts',
        description: 'Understand crypto derivatives, leverage, and risk management in a simulated trading environment.',
        xp: 250,
        badge: 'Derivatives Trader',
        isSecurityCritical: true,
      },
    ],
  },
  {
    id: 'crypto-finance',
    title: t('categories.cryptoFinance.title'),
    description: t('categories.cryptoFinance.description'),
    icon: CalculatorIcon,
    simulations: [
      {
        id: 'emergency-fund',
        title: 'Building a Crypto Emergency Fund',
        description: 'Learn how to build an emergency fund with stablecoins and earn yield on it.',
        xp: 150,
        badge: 'Recession Proof',
        icon: PiggyBankIcon,
      },
      {
        id: 'expense-tracking',
        title: 'Expense Tracking',
        description: 'Use a simple tool to track your monthly expenses and understand your liabilities.',
        xp: 100,
        badge: 'Budget Boss',
        icon: ClipboardDocumentListIcon,
      },
      {
        id: 'assets-liabilities',
        title: 'Assets vs. Liabilities',
        description: 'Visually learn the difference between assets that earn you money and liabilities that cost you money.',
        xp: 125,
        badge: 'Net Worth Ninja',
        icon: ScaleIcon,
      },
      {
        id: 'debt-repayment',
        title: 'DeFi Debt Management',
        description: 'Compare paying off high-interest debt with traditional methods vs. a lower-interest DeFi loan.',
        xp: 175,
        badge: 'Debt Slayer',
        isSecurityCritical: true,
      },
    ]
  },
  {
    id: 'tools',
    title: t('categories.tools.title'),
    description: t('categories.tools.description'),
    icon: CurrencyDollarIcon,
    simulations: [
      {
        id: 'portfolio-sim',
        title: 'Portfolio Simulator',
        description: 'Build and track a mock crypto portfolio to learn allocation strategies.',
        xp: 200,
        badge: 'Portfolio Pro'
      },
      {
        id: 'portfolio-tracker',
        title: 'Portfolio Tracker',
        description: 'Enter a mock public key to see how portfolio trackers analyze a wallet\'s assets.',
        xp: 100,
        badge: 'Asset Analyst',
        icon: WalletIcon,
      },
      {
        id: 'candlestick-chart',
        title: 'Candlestick Chart Explorer',
        description: 'Learn the basics of reading candlestick charts for technical analysis.',
        xp: 125,
        badge: 'Chart Reader',
        icon: ChartBarSquareIcon,
      },
      {
        id: 'coin-market-explorer',
        title: 'Coin Market Explorer',
        description: 'Simulate browsing a coin tracking site to understand market data.',
        xp: 75,
        badge: 'Market Observer',
        icon: TableCellsIcon,
      },
      {
        id: 'password-manager',
        title: 'Password Manager',
        description: 'Understand the importance of strong, unique passwords and password managers.',
        xp: 100,
        badge: 'Security Savvy',
        isSecurityCritical: true,
      },
      {
        id: 'liquidation-risk',
        title: 'Liquidation Risk Calculator',
        description: 'Understand how price changes can affect your borrowed positions and learn to manage risk.',
        xp: 150,
        badge: 'Risk Manager',
        icon: CalculatorIcon,
        isSecurityCritical: true,
      },
      {
        id: 'two-factor-auth',
        title: 'Two-Factor Authentication (2FA)',
        description: 'Learn how to set up and use 2FA to add a crucial layer of security to your accounts.',
        xp: 125,
        badge: 'Security Guardian',
        icon: DevicePhoneMobileIcon,
        isSecurityCritical: true,
      },
    ],
  },
];
